# Generated by Django 5.0.2 on 2024-02-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Trip", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trip",
            name="driver_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="trip",
            name="trip_id",
            field=models.CharField(max_length=10, primary_key=True, serialize=False),
        ),
    ]
